return {
  'catppuccin/nvim',
  lazy = false,
  priority = 1000,
  opts = {
    flavour = 'mocha',
    background = {
      light = 'latte',
      dark = 'mocha',
    },
    transparent_background = true,
    show_end_of_buffer = false,
    term_colors = true,
    no_italic = false,
    native_lsp = {
      enabled = true,
      virtual_text = {
        errors = { 'italic' },
        hints = { 'italic' },
        warnings = { 'italic' },
        information = { 'italic' },
      },
      underlines = {
        errors = { 'underline' },
        hints = { 'underline' },
        warnings = { 'underline' },
        information = { 'underline' },
      },
      inlay_hints = {
        inline = false,
      },
    },
    integrations = {
      cmp = true,
      gitsigns = true,
      nvimtree = true,
      treesitter = true,
      lsp_trouble = true,
      dashboard = true,
      which_key = true,
      indent_blankline = {
        enabled = true,
        colored_indent_levels = false,
      },
      mini = { enabled = false },
      barbar = true,
      bufferline = true,
      markdown = true,
      neotree = true,
      overseer = true,
      beacon = false,
      inc_rename = false,
      leap = true,
      fern = true,
      dap = {
        enabled = true,
        enable_ui = true,
      },
      harpoon = true,
      notify = true,
      telekasten = true,
      symbols_outline = true,
      multicursors = true,
      navic = {
        enabled = true,
        custom_icons = false,
      },
      hop = true,
      cursoredit = true,
      sandwich = true,
      illuminate = true,
      fidget = true,
    },
    custom_highlights = function(colors)
      return {
        TelescopeBorder = { bg = 'NONE', fg = colors.surface1 },
        TelescopePromptBorder = { bg = 'NONE', fg = colors.surface1 },
        TelescopeResultsBorder = { bg = 'NONE', fg = colors.surface1 },
        TelescopePreviewBorder = { bg = 'NONE', fg = colors.surface1 },
        TelescopeNormal = { bg = 'NONE' },
        TelescopePromptNormal = { bg = 'NONE' },
        TelescopeResultsNormal = { bg = 'NONE' },
        TelescopePreviewNormal = { bg = 'NONE' },
        TelescopeTitle = { bg = 'NONE', fg = colors.surface1 },
        TelescopePromptTitle = { bg = 'NONE', fg = colors.surface1 },
        TelescopeResultsTitle = { bg = 'NONE', fg = colors.surface1 },
        TelescopePreviewTitle = { bg = 'NONE', fg = colors.surface1 },
        CmpPmenuBorder = { bg = 'NONE', fg = colors.surface1 },
        CmpDocBorder = { bg = 'NONE', fg = colors.surface1 },
        NormalFloat = { bg = 'NONE' },
        FloatBorder = { bg = 'NONE', fg = colors.surface1 },
        FloatTitle = { bg = 'NONE', fg = colors.surface1 },
        Pmenu = { bg = 'NONE' },
        LspFloatWinNormal = { bg = 'NONE' },
        LspFloatWinBorder = { bg = 'NONE', fg = colors.surface1 },
      }
    end,
  },
  config = function(_, opts)
    require('catppuccin').setup(opts)
    vim.cmd.colorscheme 'catppuccin'
  end,
}
